name: Revert Last Commit
on:
  push:
    branches:
      - main
jobs:
  revert-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Revert Last Commit
      run: |
        git log --pretty=format:"%h - %an, %ar : %s"
        git reset HEAD~1
        
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4.7.2
      with:
        commit_message: Revert last commit test
