name: Revert Last Commit
on:
  push:
    branches:
      - dev
jobs:
  revert-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Revert Last Commit
      run: git reset HEAD~1
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4.7.2
      with:
        commit_message: Revert last commit
